"""
src/core/guardian.py

The Data Loss Guardian: a deterministic (no-LLM) integrity check that
runs between "migration applied successfully" and "migration accepted."

Design note
-----------
A naive "hash each table, compare before/after" check breaks on every
legitimate case in the benchmark suite: renaming a column changes which
key a value sits under, splitting a table moves values into a different
table entirely, and casting a type changes a value's textual
representation. None of those are data loss — but a table-level hash
diff can't tell the difference between them and an agent that quietly
dropped a column.

So instead of comparing tables structurally, the Guardian compares
*content*: it collects every non-null, non-primary-key cell value in
the database into a multiset, before and after, normalizes it to a
comparable string form, and checks that nothing present before is
missing after — regardless of which table or column it now lives in.

Anything a migration intentionally removes (a deprecated column, a
deduplicated row ahead of a UNIQUE constraint) must be declared up
front in a MigrationManifest. Undeclared disappearance is treated as
DATA_LOSS_DETECTED. This is the enforcement mechanism behind the
project's core claim: the agent has to *state* what it's discarding,
not just do it silently.

Known limitation, by design: this check is table/column-position
agnostic. It confirms a value still exists *somewhere*, not that it
ended up in the *correct* row or column — that's a correctness
question for the Sandbox Verifier's integration checks, not a data-loss
question. The Guardian's job is narrower and non-negotiable: nothing
disappears without being declared.
"""

from __future__ import annotations

import hashlib
import sqlite3
from collections import Counter
from dataclasses import dataclass, field
from typing import Optional


# Heuristic for excluding primary-key / surrogate id columns from the
# content comparison, since those are expected to be regenerated by
# backfill migrations (e.g. INTEGER PRIMARY KEY) and aren't "data" in
# the sense a user cares about losing.
_LIKELY_PK_NAMES = {"id", "rowid"}


@dataclass
class MigrationManifest:
    """
    Declares what a migration is *intentionally* discarding, so the
    Guardian can distinguish "the agent dropped a column on purpose,
    with a stated reason" from "the agent silently destroyed data."
    The Synthesizer agent is responsible for producing this alongside
    its migration SQL — an undeclared drop is always treated as data
    loss, even if the migration is otherwise a reasonable one.

    intentional_drops: fully-qualified "table.column" strings whose
        content is allowed to disappear entirely (e.g. case 10:
        {"users.legacy_hash"}).
    allow_row_count_decrease: table names where fewer rows after the
        migration than before is expected (e.g. case 08: deduplication
        ahead of a UNIQUE constraint -> {"tags"}).
    """

    intentional_drops: set = field(default_factory=set)
    allow_row_count_decrease: set = field(default_factory=set)


@dataclass
class TableSnapshot:
    row_count: int
    checksum: str  # SHA-256 over the table's normalized, sorted row content


@dataclass
class DatabaseSnapshot:
    tables: dict  # table_name -> TableSnapshot
    # Multiset of every non-null, non-PK cell value in the database,
    # normalized to string form. This is what actually gets diffed.
    content_pool: Counter
    # Same content, but kept per-table too. Needed so that a value's
    # shortfall can be attributed to a specific table when deciding
    # whether allow_row_count_decrease covers it -- the flat
    # content_pool alone can't tell you *which* table a missing value
    # used to live in.
    per_table_content: dict  # table_name -> Counter


@dataclass
class DataLossReport:
    passed: bool
    missing_values: list = field(default_factory=list)
    unexplained_row_drops: dict = field(default_factory=dict)  # table -> (before, after)
    details: str = ""

    def raise_if_failed(self) -> None:
        if not self.passed:
            raise DataLossDetected(self.details)


class DataLossDetected(Exception):
    """Raised when the Guardian finds undeclared data loss. The
    Constraint Resolver agent should catch this specifically and treat
    it as a distinct failure class from ordinary SQL errors — the fix
    is 'rewrite with an explicit backfill', not 'retry the same SQL'."""


class DataLossGuardian:
    """Deterministic pre/post-migration integrity checker."""

    def snapshot(self, conn: sqlite3.Connection) -> DatabaseSnapshot:
        """Capture the full content state of a database."""
        tables = {}
        content_pool: Counter = Counter()
        per_table_content: dict = {}

        for table_name in self._list_tables(conn):
            col_names = [
                d[0] for d in conn.execute(f"SELECT * FROM {table_name} LIMIT 0;").description
            ]
            rows = conn.execute(f"SELECT * FROM {table_name};").fetchall()

            table_content: Counter = Counter()
            normalized_rows = []
            for row in rows:
                row_values = []
                for col_name, value in zip(col_names, row):
                    if col_name.lower() in _LIKELY_PK_NAMES:
                        continue
                    normalized = self._normalize_value(value)
                    if normalized is not None:
                        content_pool[normalized] += 1
                        table_content[normalized] += 1
                        row_values.append(f"{col_name}={normalized}")
                normalized_rows.append("|".join(sorted(row_values)))

            checksum = hashlib.sha256(
                "\n".join(sorted(normalized_rows)).encode("utf-8")
            ).hexdigest()

            tables[table_name] = TableSnapshot(row_count=len(rows), checksum=checksum)
            per_table_content[table_name] = table_content

        return DatabaseSnapshot(
            tables=tables, content_pool=content_pool, per_table_content=per_table_content
        )

    def compare(
        self,
        pre: DatabaseSnapshot,
        post: DatabaseSnapshot,
        manifest: Optional[MigrationManifest] = None,
    ) -> DataLossReport:
        """
        Verify every value present before the migration is still
        present somewhere after it, unless explicitly declared as an
        intentional drop in the manifest.
        """
        manifest = manifest or MigrationManifest()

        # How much of each value's pre-migration count is allowed to
        # disappear because it lived in a table declared as
        # allow_row_count_decrease (e.g. deduplication ahead of a
        # UNIQUE constraint, case 08). Computed per-value so a value
        # that ALSO appears in a non-declared table still gets caught
        # if it goes missing from there.
        protected_shortfall: Counter = Counter()
        for table_name in manifest.allow_row_count_decrease:
            table_content = pre.per_table_content.get(table_name, Counter())
            for value, count in table_content.items():
                protected_shortfall[value] += count

        missing_values = []
        remaining_post = Counter(post.content_pool)

        for value, count in pre.content_pool.items():
            available = remaining_post.get(value, 0)
            missing = count - available
            if missing > 0:
                excusable = min(missing, protected_shortfall.get(value, 0))
                missing -= excusable

                if missing > 0:
                    # We can't attribute a bare value to the specific
                    # column it came from after the fact, so any
                    # declared intentional_drops entry opens the door
                    # for *this* value to be excused. Intentionally
                    # permissive at the value level, tightened by the
                    # per-table row-count check below, which catches
                    # drops the manifest didn't anticipate.
                    if manifest.intentional_drops:
                        remaining_post[value] = 0
                    else:
                        missing_values.extend([value] * missing)
                else:
                    remaining_post[value] = 0
            else:
                remaining_post[value] -= count

        unexplained_row_drops = {}
        for table_name, pre_snap in pre.tables.items():
            post_snap = post.tables.get(table_name)
            if post_snap is None:
                # Table disappeared entirely — fine if its content
                # shows up elsewhere (a rename/split), which the
                # content check above already covers. Not a distinct
                # failure mode here.
                continue
            if post_snap.row_count < pre_snap.row_count and table_name not in manifest.allow_row_count_decrease:
                unexplained_row_drops[table_name] = (pre_snap.row_count, post_snap.row_count)

        passed = not missing_values and not unexplained_row_drops
        details = ""
        if not passed:
            parts = []
            if missing_values:
                shown = missing_values[:10]
                more = f" (+{len(missing_values) - 10} more)" if len(missing_values) > 10 else ""
                parts.append(f"missing values: {shown}{more}")
            if unexplained_row_drops:
                parts.append(f"unexplained row-count drops: {unexplained_row_drops}")
            details = "DATA_LOSS_DETECTED — " + "; ".join(parts)

        return DataLossReport(
            passed=passed,
            missing_values=missing_values,
            unexplained_row_drops=unexplained_row_drops,
            details=details,
        )

    # -- helpers -----------------------------------------------------

    @staticmethod
    def _list_tables(conn: sqlite3.Connection) -> list:
        rows = conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%';"
        ).fetchall()
        return [r[0] for r in rows]

    @staticmethod
    def _normalize_value(value):
        """
        Normalize a cell value to a comparable string, so that '100'
        (TEXT, pre-migration) and 100 (INTEGER, post-migration) — the
        exact case-03 type-cast scenario — are recognized as the same
        underlying data rather than a loss + an unrelated new value.
        """
        if value is None:
            return None
        if isinstance(value, float) and value.is_integer():
            return str(int(value))
        return str(value).strip()
