"""
demo/generate_demo_data.py

Reads the real, already-committed evaluation output -- results/*.json,
trajectories/*/*.json, README.md's Hot Take section -- and writes
demo/data.js: the only data demo/index.html ever reads.

No live API calls, no fabricated example data. If a source file is
missing this raises instead of silently falling back to placeholder
content, since a demo page showing made-up numbers would defeat the
entire point of grounding it in real evidence.

Reuses src/evaluate.py's verdict logic rather than reimplementing it,
so the demo table can never drift out of sync with `make evaluate`'s
results/comparison.md.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from src.evaluate import _advanced_verdict, _baseline_verdict, _is_improved

ROOT = Path(__file__).resolve().parent.parent
REPLAY_CASE = "08_composite_unique_index"


def load_results(results_dir: Path) -> tuple[dict, dict]:
    baseline = {e["case_name"]: e for e in json.loads((results_dir / "baseline_results.json").read_text())}
    advanced = {e["case_name"]: e for e in json.loads((results_dir / "advanced_results.json").read_text())}
    return baseline, advanced


def build_comparison(baseline: dict, advanced: dict) -> list:
    rows = []
    for case_name in sorted(set(baseline) | set(advanced)):
        b_verdict = _baseline_verdict(baseline.get(case_name))
        a_verdict = _advanced_verdict(advanced.get(case_name))
        rows.append(
            {
                "case": case_name,
                "baseline": b_verdict,
                "advanced": a_verdict,
                "improved": _is_improved(b_verdict, a_verdict),
            }
        )
    return rows


def extract_hot_take(readme_text: str) -> str:
    """Pull the '## Hot Take' section verbatim (heading excluded) up to
    the next '## ' heading, so the demo page quotes README.md exactly
    instead of a copy that can silently drift out of sync with it."""
    match = re.search(r"^## Hot Take\s*\n(.*?)(?=\n## |\Z)", readme_text, re.S | re.M)
    if not match:
        raise ValueError("README.md has no '## Hot Take' section")
    return match.group(1).strip()


def load_trajectory(trajectories_dir: Path, case_name: str, kind: str) -> dict:
    return json.loads((trajectories_dir / kind / f"{case_name}.json").read_text())


def build_demo_data(root: Path = ROOT) -> dict:
    baseline, advanced = load_results(root / "results")
    return {
        "comparison": build_comparison(baseline, advanced),
        "hot_take": extract_hot_take((root / "README.md").read_text()),
        "replay_case": REPLAY_CASE,
        "replay_baseline_trajectory": load_trajectory(root / "trajectories", REPLAY_CASE, "baseline"),
        "replay_advanced_trajectory": load_trajectory(root / "trajectories", REPLAY_CASE, "advanced"),
    }


def main() -> None:
    data = build_demo_data()
    out_path = ROOT / "demo" / "data.js"
    out_path.write_text("// generated by demo/generate_demo_data.py -- do not edit by hand\n"
                         "const DEMO_DATA = " + json.dumps(data, indent=2) + ";\n")
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
